### PR TITLE
Update MAINTAINERS

### PR DESCRIPTION
**Pull request by seaneagan**

### CODE REVIEW

**Review by hiddeco — COMMENTED** [review]
Given the maintainers list is in alphabetical order, I think you should be listed second.

**Review by stefanprodan — APPROVED** [review]
LGTM 🎉

**Comment by seaneagan** [comment]
> Given the maintainers list is in alphabetical order, I think you should be listed second.

Fixed now.

**Review by hiddeco — APPROVED** [review]

**Comment by hiddeco** [comment]
@seaneagan welcome to the bright/dark side (you choose) :sunflower: :tada:

**Pull request merged**
