### PR TITLE
doc: fix HelmRelease default value for `.spec.upgrade.crds`

### PR DESCRIPTION
**Pull request by sestegra**
In the HelmRelease documentation, the default value for `.spec.upgrade.crds` is set as `None` in [Upgrade configuration](https://fluxcd.io/flux/components/helm/helmreleases/#upgrade-configuration) part, then the default value is set as `Skip` in [Controlling the lifecycle of Custom Resource Definitions](https://fluxcd.io/flux/components/helm/helmreleases/#controlling-the-lifecycle-of-custom-resource-definitions) part.

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @sestegra 🥇 

PS. Please rebase

**Comment by sestegra** [comment]
@stefanprodan Update done

**Comment by stefanprodan** [comment]
Ah I haven't noticed the merge commit... @souleb  we need to figure out a way to block users from doing this.

**Comment by sestegra** [comment]
Sorry for the extra manual labor, I owe you a drink
I found some open discussions about this issue, but no solutions found yet.
- https://github.com/orgs/community/discussions/3245
- https://github.com/orgs/community/discussions/13749

**Pull request merged**
