### PR TITLE
Update helm to 3.7.2

### PR DESCRIPTION
**Pull request by cbuto**
After upgrading to Flux 0.25.3, we noticed the memory discussed in a few different issues fluxcd/helm-controller#349, fluxcd/helm-controller#351, and fluxcd/helm-controller#345 started happening again (after pinning the helm-controller to 0.12.2, the issue went away).

The original update to helm 3.7.2 was in this [PR](https://github.com/fluxcd/helm-controller/pull/380) but ended up getting downgraded to 3.7.1 in a subsequent PR.

Hopefully this update resolves the memory issues! 🎉 

Signed-off-by: Casey Buto <cbuto@d2iq.com>

### CODE REVIEW

**Review by makkes — APPROVED** [review]

**Comment by stefanprodan** [comment]
@cbuto have you tested this change and the memory issue went away?

**Comment by cbuto** [comment]
> @cbuto have you tested this change and the memory issue went away?

@stefanprodan I didn't get a chance to test it fully, going to give it a go now though and see what happens!

**Comment by cbuto** [comment]
@stefanprodan unfortunately, it looks like a memory issue might still exist (at least in our tests) with the helm-controller configured with 1Gi and 1.5Gi of memory.

**Comment by stefanprodan** [comment]
@cbuto could you please test with helm 3.8.0?

**Comment by cbuto** [comment]
@stefanprodan I can give that a go for sure, I did see there is actually some more work being done addressing memory issues here https://github.com/helm/helm/pull/10486 that could be related (hard to tell right now)

**Comment by hiddeco** [comment]
I suspect the PR you are referring to is indeed the thing that (hopefully) resolves this all, and also explains some of the other weird behavior that has been reported recently (about all releases failing).

**Pull request merged**
